"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "af";

export const translations = {
  en: {
    nav_home: "Home", nav_platform: "Platform", nav_for_schools: "For Institutions", nav_inst_schools: "For Schools", nav_inst_parents: "For Parents", nav_inst_universities: "For Universities", nav_inst_schools_sub: "Guidance infrastructure for high schools", nav_inst_parents_sub: "Stay close to your child's journey", nav_inst_universities_sub: "Smarter student recruitment", nav_how_it_works: "How It Works", nav_early_access: "Early Access", nav_cta: "Request Access",
    hero_badge: "South Africa's First Education AI", hero_line1: "The decision made", hero_line2: "in Grade 9", hero_line3: "determines", hero_accent: "everything", hero_line4: "that follows.", hero_sub: "AI-powered career guidance for South African learners, starting Grade 9. Free for students, always.", hero_cta1: "Request Early Access", hero_cta2: "See the Platform", trust_1: "Grade 9 to Postgrad", trust_2: "AI + Psychometrics", trust_3: "Free for Students", trust_4: "SA-Built · SA-Focused",
    problem_label: "The Problem", problem_h2_1: "South Africa has a", problem_h2_2: "Grade 9 decision gap.", problem_sub: "Subject selection shapes every career option that follows. Most learners make this decision without any real guidance.", problem_stat1_h: "of learners choose subjects without guidance", problem_stat1_b: "Grade 10 subject choices are made on instinct, not intelligence.", problem_stat2_h: "is when most career planning begins", problem_stat2_b: "By Grade 12, critical subject doors are already permanently closed.", problem_stat3_h: "information gap across SA schools", problem_stat3_b: "Schools, parents, and institutions are all operating blind.", problem_stat4_h: "invested in learner decision support", problem_stat4_b: "Billions go into education delivery. Near-zero goes into the decision layer.",
    stats_label: "Our Reach", stats_h2_a: "Built to reach every", stats_h2_b: "South African learner.", stats_sub: "Starting in Gauteng, expanding to every province. Free for every learner.", stats_n1_unit: "k+", stats_n1_label: "Students, Year 1 Target", stats_n1_note: "Every Grade 9 learner in Gauteng, regardless of school type or family income", stats_n2_unit: " provinces", stats_n2_label: "National Reach by Year 3", stats_n2_note: "Starting in Gauteng, expanding to every province. Every learner deserves guidance.", stats_n3_unit: " student cost", stats_n3_label: "Always free for learners", stats_n3_note: "Funded by institutions and schools. Students never pay. Equitable guidance is the mission.",
    platform_label: "The Platform", plat_h2_a: "Decision intelligence.", plat_h2_b: "Not information.", plat_body: "Six intelligence systems, one platform. Built to guide every South African learner from first subject choice to career.", plat_p1_title: "AI Recommendation Engine", plat_p1_body: "Personalised career scores, subject picks, APS targets, and institution matching. Updated continuously as you grow.", plat_p2_title: "Psychometric Analysis", plat_p2_body: "Personality profiling, learning style detection, and motivation modelling. Not a quiz, a genuinely intelligent system.", plat_p3_title: "Predictive Analytics", plat_p3_body: "APS trajectory forecasting, academic decline detection, and early intervention triggers before problems become permanent.", plat_p4_title: "Gamification System", plat_p4_body: "Career missions, badges, and skill discovery games designed to keep learners engaged from Grade 9 all the way through.", plat_p5_title: "Learner Portfolio", plat_p5_body: "An academic and personal profile that travels from Grade 9 to employment. Longitudinal intelligence built over years of use.", plat_p6_title: "Application Management", plat_p6_body: "Apply to universities, TVET colleges, and skills programmes in one place, with fit-score intelligence guiding every choice.",
    features_label: "Features", features_h2: "Every tool you need to outperform.", features_sub: "Designed from the ground up for the NSC, the IEB, and the institutions South African students actually attend — not adapted from abroad.", feat_f1_title: "AI Study Plans", feat_f1_body: "A personalised roadmap that updates based on your progress, upcoming exams, and identified gaps. Not a generic timetable.", feat_f2_title: "Past Paper Intelligence", feat_f2_body: "10+ years of NSC and IEB papers analysed. Know which topics carry the most weight, what question formats to expect, and where you're most exposed.", feat_f3_title: "Institution Analytics", feat_f3_body: "Understand exactly what your target university and faculty expect. See how your current performance maps to real admission benchmarks.", feat_f4_title: "Progress Tracking", feat_f4_body: "Subject mastery scores, daily streaks, and weekly summaries so you always know where you stand and what needs work before it's too late.", feat_f5_title: "Focused Study Sessions", feat_f5_body: "Structured, distraction-free sessions with adaptive question sets that push you toward mastery, not just familiarity.", feat_f6_title: "Built for SA, All Levels", feat_f6_body: "From matric to postgrad, YourUniverse adapts to your level, your curriculum, and your goals. No one-size-fits-all.",
    comp_label: "How We Compare", comp_h2_1: "Not just another", comp_h2_2: "career website.", comp_sub: "Traditional platforms show lists of careers and requirements. YourUniverse understands who you are and builds a personalised roadmap — from Grade 9, all the way to your future.", comp_hdr_feature: "Feature", comp_hdr_trad: "Traditional Platforms", comp_mobile_other: "Others", comp_mobile_us: "Us", comp_r1_feat: "Career guidance model", comp_r1_them: "Static directory", comp_r1_us: "AI decision intelligence", comp_r2_feat: "Guidance timing", comp_r2_them: "Grade 11–12", comp_r2_us: "Grade 9 onward", comp_r3_feat: "Psychometric analysis", comp_r3_them: "None", comp_r3_us: "Full behavioural profiling", comp_r4_feat: "Who it supports", comp_r4_them: "Student only", comp_r4_us: "Students, schools, parents, universities", comp_r5_feat: "Parent visibility", comp_r5_them: "None", comp_r5_us: "Real-time monitoring dashboard", comp_r6_feat: "APS intelligence", comp_r6_them: "None", comp_r6_us: "Live APS tracking and forecasting", comp_r7_feat: "Gamification", comp_r7_them: "None", comp_r7_us: "Career missions, badges, progression", comp_r8_feat: "Application management", comp_r8_them: "Separate utility", comp_r8_us: "Embedded, fit-scored, unified",
    journey_label: "Your Journey", journey_h2: "One platform. Every step.", journey_h2_a: "From Grade 9", journey_h2_b: "to graduation", journey_h2_c: "and beyond.", journey_sub: "Six phases. One continuous system that grows with you — from Grade 9 through to your career.", phase1_name: "Grade 9 Onboarding", phase1_head: "Your journey starts here.", phase1_body: "Complete your psychometric profile and unlock more career insight than most counsellors gather in a year.", phase2_name: "Subject Selection Intelligence", phase2_head: "Choose subjects that open doors.", phase2_body: "AI recommends Grade 10 subjects based on your interests, aptitude, and where you want to go.", phase3_name: "Continuous Monitoring", phase3_head: "No learner quietly falls behind.", phase3_body: "APS tracking, performance alerts, and adaptive guidance keep you on course and keep parents informed.", phase4_name: "Career Mapping", phase4_head: "Your plan evolves as you do.", phase4_body: "Career recommendations update as your grades improve, interests shift, and the job market changes.", phase5_name: "Application Management", phase5_head: "One portal. Every institution.", phase5_body: "Apply to universities, TVET colleges, and skills programmes with fit-score intelligence guiding every step.", phase6_name: "Institutional Matching", phase6_head: "The right institution finds you.", phase6_body: "Institutions access your profile and reach out based on genuine fit, not blind mass recruitment.",
    eco_label: "Who It Serves", eco_h2_1: "Built for every student.", eco_h2_2: "Backed by", eco_h2_3: "everyone around them.", eco_sub: "One platform built around the student, supported by schools, parents, and universities. Students always get free access.", eco_s1_title: "For Students", eco_s1_sub: "Every feature, always free.", eco_s1_cta: "Free for every learner, always", eco_s1_f1: "AI-powered career profiling", eco_s1_f2: "Personalised subject recommendations", eco_s1_f3: "APS target tracking & forecasting", eco_s1_f4: "University & TVET application hub", eco_s1_f5: "Gamified career exploration missions", eco_s1_f6: "Personal development portfolio", eco_s2_title: "For Schools", eco_s2_sub: "Whole-school guidance, simplified.", eco_s2_cta: "Empowering school counsellors", eco_s2_f1: "Learner dashboards for every class", eco_s2_f2: "Grade 9 counselling infrastructure", eco_s2_f3: "Automated guidance workflows", eco_s2_f4: "Early alerts for at-risk learners", eco_s2_f5: "Performance benchmarking", eco_s2_f6: "School-wide reporting tools", eco_s3_title: "For Parents", eco_s3_sub: "Stay close to your child's future.", eco_s3_cta: "Visibility when it matters most", eco_s3_f1: "Real-time academic progress view", eco_s3_f2: "Early decline alerts", eco_s3_f3: "Career pathway updates", eco_s3_f4: "APS target monitoring", eco_s3_f5: "Application status tracking", eco_s3_f6: "Career readiness reports", eco_s4_title: "For Universities & TVETs", eco_s4_sub: "Find the right students, faster.", eco_s4_cta: "Smarter student recruitment", eco_s4_f1: "Pre-qualified student pipelines", eco_s4_f2: "Student success likelihood scores", eco_s4_f3: "Fit-matched recruitment tools", eco_s4_f4: "Readiness analytics per programme", eco_s4_f5: "Smarter admissions intelligence", eco_s4_f6: "Programme demand trend data",
    who_label: "Who It's For", who_h2: "Built for every stage of your journey.", who_sub: "Whether you're writing matric, navigating first year, or completing your honours, YourUniverse adapts to your level and your goals.", who_p1_title: "The Matric Student", who_p1_quote: "I have a university in mind and I need to actually get in.", who_p1_body: "YourUniverse maps your study plan directly to your target institution's admission requirements. You study what counts, in the way that counts.", who_p2_title: "The First-Year Student", who_p2_quote: "University is a completely different world and I wasn't ready.", who_p2_body: "The jump from matric to university is brutal without support. YourUniverse builds the academic habits and structure that first-years need to survive and thrive.", who_p3_title: "The Postgrad Learner", who_p3_quote: "I need focus, structure, and a way to track long-form progress.", who_p3_body: "Deep work requires a different kind of support. YourUniverse provides focused sessions, research milestones, and academic writing tools for postgraduate learners.",
    waitlist_label: "Early Access", waitlist_h2_1: "Join the", waitlist_h2_2: "first cohort.", waitlist_sub: "Limited early access for SA schools and learners. Be first in line.", wait_type_label: "I am a", wait_type_heading: "Who are you joining as?", wait_t_student: "Student", wait_t_student_sub: "Grade 9 – Postgrad", wait_t_parent: "Parent", wait_t_parent_sub: "Supporting my child", wait_t_school: "Educator / School", wait_t_school_sub: "Primary or secondary", wait_t_inst: "University / TVET", wait_t_inst_sub: "Higher education", wait_step: "Step", wait_of: "of", wait_review_lbl: "Review", wait_firstname_q: "What's your first name?", wait_firstname_hint: "We'll personalise your experience based on your name.", wait_firstname_ph: "e.g. Amahle", wait_surname_q: "What's your surname?", wait_surname_ph: "e.g. Dlamini", wait_email_q: "What's your email address?", wait_email_hint: "We'll send your confirmation and notify you at launch.", wait_email_ph: "you@example.com", wait_email_nospam: "No spam. Unsubscribe any time.", wait_org_school_q: "Which school do you represent?", wait_org_parent_q: "What school does your child attend? (optional)", wait_org_inst_q: "Which institution are you from?", wait_org_hint: "This helps us match you with the right cohort.", wait_org_school_ph: "e.g. Parktown Boys' High", wait_org_parent_ph: "e.g. St Mary's DSG", wait_org_inst_ph: "e.g. University of Pretoria", wait_back: "Back", wait_continue: "Continue", wait_review_btn: "Review", wait_rev_heading: "Looks good", wait_rev_sub: "Review your details before joining the waitlist.", wait_rev_type: "Type", wait_rev_name: "Name", wait_rev_email: "Email", wait_rev_org: "Organisation", wait_submit: "Confirm & Join Waitlist", wait_joining: "Joining waitlist\u2026", wait_footer: "Made in South Africa \u00b7 Free for every student, always.", wait_success_h: "You're on the list.", wait_success_p: "A confirmation is headed to", wait_success_end: "You're part of the infrastructure shaping Africa's educational future.", wait_press_enter: "Press", wait_to_continue: "to continue",
    schools_badge: "Institutional Partners", schools_h1_1: "Built for", schools_h1_2: "every", schools_h1_3: "stakeholder in education", schools_sub: "Students learn. Schools guide. Universities recruit. Businesses discover talent. YourUniverse serves the entire ecosystem — one platform, one mission.",
    plat_page_badge: "Platform Technology", plat_page_h1_1: "Six intelligence systems.", plat_page_h1_2: "One unified platform.", plat_page_sub: "Built from the ground up for South African learners, schools, and institutions. No adapted foreign software. Purpose-built for the NSC, the IEB, and SA's unique career landscape.",
    foot_tagline: "South Africa's first educational decision-intelligence platform — guiding learners from Grade 9 to graduation and beyond.", foot_product_of: "A product of", foot_col_platform: "Platform", foot_col_company: "Company", foot_col_legal: "Legal", foot_how_it_works: "How It Works", foot_ai_features: "AI Features", foot_for_schools: "For Schools", foot_for_inst: "For Institutions", foot_req_access: "Request Early Access", foot_about: "About Us", foot_lynxio: "Lynxio Tech", foot_careers: "Careers", foot_privacy: "Privacy Policy", foot_terms: "Terms of Service", foot_data: "Data Protection", foot_copyright: "All rights reserved. Built in South Africa.",
    loading_label: "Initialising", footer_rights: "All rights reserved.",
    waitlist_name: "Full name", waitlist_email: "Email address", waitlist_role: "I am a...", waitlist_cta: "Request Early Access",
  },

  af: {
    nav_home: "Tuis", nav_platform: "Platform", nav_for_schools: "Vir Instellings", nav_inst_schools: "Vir Skole", nav_inst_parents: "Vir Ouers", nav_inst_universities: "Vir Universiteite", nav_inst_schools_sub: "Leiding vir ho\u00ebrskole", nav_inst_parents_sub: "Bly betrokke by jou kind se reis", nav_inst_universities_sub: "Slimmer studentewerwing", nav_how_it_works: "Hoe Dit Werk", nav_early_access: "Vroe\u00eb Toegang", nav_cta: "Versoek Toegang",
    hero_badge: "Suid-Afrika se Eerste Onderwys-KI", hero_line1: "Die besluit wat", hero_line2: "in Graad 9 geneem word", hero_line3: "bepaal", hero_accent: "alles", hero_line4: "wat volg.", hero_sub: "KI-aangedrewe loopbaanleiding vir Suid-Afrikaanse leerders, van Graad 9 af. Altyd gratis vir studente.", hero_cta1: "Versoek Vroe\u00eb Toegang", hero_cta2: "Sien die Platform", trust_1: "Graad 9 tot Nagraads", trust_2: "KI + Psigometrie", trust_3: "Gratis vir Studente", trust_4: "SA-Gebou \u00b7 SA-Gefokus",
    problem_label: "Die Probleem", problem_h2_1: "Suid-Afrika het \u2019n", problem_h2_2: "Graad 9-besluitgaping.", problem_sub: "Vakkeuse bepaal elke loopbaanopsie wat volg. Die meeste leerders maak hierdie besluit sonder enige leiding.", problem_stat1_h: "van leerders kies vakke sonder behoorlike leiding", problem_stat1_b: "Graad 10-vakkeuses word op instink gemaak, nie op intelligensie nie.", problem_stat2_h: "is wanneer die meeste loopbaanbeplanning eers begin", problem_stat2_b: "Teen Graad 12 is kritieke vakdeure reeds permanent gesluit.", problem_stat3_h: "inligtingsgaping oor SA-skole heen", problem_stat3_b: "Skole, ouers en instellings werk almal blind.", problem_stat4_h: "bel\u00ea in leerder-besluitondersteuning", problem_stat4_b: "Miljarde gaan na onderwysverskaffing. Bykans niks gaan na die besluitlaag nie.",
    stats_label: "Ons Bereik", stats_h2_a: "Gebou om elke", stats_h2_b: "Suid-Afrikaanse leerder bereik.", stats_sub: "Begin in Gauteng, uitgebrei na elke provinsie. Gratis vir elke leerder.", stats_n1_unit: "k+", stats_n1_label: "Studente, Jaar 1 Teiken", stats_n1_note: "Elke Graad 9-leerder in Gauteng, ongeag skooltipe of gesinsinkomste", stats_n2_unit: " provinsies", stats_n2_label: "Nasionale Bereik teen Jaar 3", stats_n2_note: "Begin in Gauteng, uitgebrei na elke provinsie. Elke leerder verdien leiding.", stats_n3_unit: " studentekoste", stats_n3_label: "Altyd gratis vir leerders", stats_n3_note: "Gefinansier deur instellings en skole. Studente betaal nooit. Gelyke leiding is die missie.",
    platform_label: "Die Platform", plat_h2_a: "Besluitintelligensie.", plat_h2_b: "Nie net inligting nie.", plat_body: "Ses intelligensiesisteme, een platform. Gebou om elke Suid-Afrikaanse leerder te lei van eerste vakkeuse tot loopbaan.", plat_p1_title: "KI-Aanbevelingsenjin", plat_p1_body: "Persoonlike loopbaantelling, vakkeuses, APS-teikens en instellingpassing. Deurlopend bygewerk soos jy groei.", plat_p2_title: "Psigometriese Analise", plat_p2_body: "Persoonlikheidsprofiel, leerstylherkenning en motiveringsmodellering. Nie \u2019n gewone toets nie \u2014 \u2019n werklik intelligente stelsel.", plat_p3_title: "Voorspellende Analise", plat_p3_body: "APS-trajekvoorspelling, akademiese agterstands-opsporing en vroe\u00eb ingrypingseine \u2014 voordat probleme permanent word.", plat_p4_title: "Gamifikasiestelsel", plat_p4_body: "Loopbaanmissies, kentekens en vaardigheidontdekkingspeletjies wat leerders betrokke hou van Graad 9 al die pad deur.", plat_p5_title: "Leerder-Portfolio", plat_p5_body: "\u2019n Akademiese en persoonlike profiel wat jou van Graad 9 tot indiensneming vergesel. Langtermynintelligensie gebou oor jare van gebruik.", plat_p6_title: "Aansoekbestuursstelsel", plat_p6_body: "Doen aansoek by universiteite, TVET-kolleges en vaardigheidsprogramme op een plek, met passings-intelligensie wat elke keuse lei.",
    features_label: "Kenmerke", features_h2: "Elke hulpmiddel wat jy nodig het om uit te presteer.", features_sub: "Van grond af ontwerp vir die NSS, die IEB en die instellings wat Suid-Afrikaanse studente werklik bywoon — nie van oorsee aangepas nie.", feat_f1_title: "KI-Studieplane", feat_f1_body: "\u2019n Persoonlike padkaart wat bywerk op grond van jou vordering, komende eksamens en ge\u00efdentifiseerde leemtes. Nie \u2019n generiese rooster nie.", feat_f2_title: "Vorige-vraestel-intelligensie", feat_f2_body: "Meer as 10 jaar se NSS- en IEB-vraestelle geanaliseer. Weet watter onderwerpe die meeste gewig dra, watter vraagformate om te verwag en waar jy die kwesbaars is.", feat_f3_title: "Instellinganalitika", feat_f3_body: "Verstaan presies wat jou teikenuniversiteit en -fakulteit verwag. Sien hoe jou huidige prestasie vergelyk met werklike toelatingsvereistes.", feat_f4_title: "Vorderingsopvolging", feat_f4_body: "Vakmeesteringtellings, daaglikse reekse en weeklikse opsommings sodat jy altyd weet waar jy staan en wat werk benodig voor dit te laat is.", feat_f5_title: "Gefokusde Studiesessies", feat_f5_body: "Gestruktureerde, afleidingvrye sessies met aanpasbare vraagstel­le wat jou na meesterskap dryf — nie net oppervlakige vertroudheid nie.", feat_f6_title: "Gebou vir SA, Alle Vlakke", feat_f6_body: "Van matriek tot nagraads pas YourUniverse aan by jou vlak, jou kurrikulum en jou doelwitte. Geen eengrootte-pas-almal nie.",
    comp_label: "Hoe Ons Vergelyk", comp_h2_1: "Nie net nog \u2019n", comp_h2_2: "loopbaanwebwerf nie.", comp_sub: "Tradisionele platforms wys bloot lyste van loopbane en vereistes. YourUniverse verstaan wie j\u00fd is en bou \u2019n persoonlike padkaart \u2014 vanaf Graad 9, al die pad na jou toekoms.", comp_hdr_feature: "Kenmerk", comp_hdr_trad: "Tradisionele Platforms", comp_mobile_other: "Ander", comp_mobile_us: "Ons", comp_r1_feat: "Loopbaanleidingsmodel", comp_r1_them: "Statiese gids", comp_r1_us: "KI-besluitintelligensie", comp_r2_feat: "Leidingstydperk", comp_r2_them: "Graad 11\u201312", comp_r2_us: "Vanaf Graad 9", comp_r3_feat: "Psigometriese analise", comp_r3_them: "Geen", comp_r3_us: "Volledige gedragsprofiel", comp_r4_feat: "Wie dit ondersteun", comp_r4_them: "Slegs student", comp_r4_us: "Studente, skole, ouers, universiteite", comp_r5_feat: "Ouersigbaarheid", comp_r5_them: "Geen", comp_r5_us: "Intydse moniteringsdashboard", comp_r6_feat: "APS-intelligensie", comp_r6_them: "Geen", comp_r6_us: "Lewendige APS-opvolging en -voorspelling", comp_r7_feat: "Gamifikasie", comp_r7_them: "Geen", comp_r7_us: "Loopbaanmissies, kentekens, vordering", comp_r8_feat: "Aansoekbestuur", comp_r8_them: "Afsonderlike hulpmiddel", comp_r8_us: "Ingebou, passend, volledig ge\u00efntegreer",
    journey_label: "Jou Reis", journey_h2: "Een platform. Elke stap.", journey_h2_a: "Van Graad 9", journey_h2_b: "tot graduering", journey_h2_c: "en verder.", journey_sub: "Ses fases. Een deurlopende stelsel wat saam met jou groei — van Graad 9 tot jou loopbaan.", phase1_name: "Graad 9 Inskrywing", phase1_head: "Jou reis begin hier.", phase1_body: "Voltooi jou psigometriese profiel en ontsluit meer loopbaaninsig as wat die meeste beraders in \u2019n jaar bied.", phase2_name: "Vakseleksie-intelligensie", phase2_head: "Kies vakke wat deure oopmaak.", phase2_body: "KI beveel Graad 10-vakke aan op grond van jou belangstellings, aanleg en waar jy heen wil.", phase3_name: "Deurlopende Monitering", phase3_head: "Geen leerder bly stil agter nie.", phase3_body: "APS-opvolging, prestasiewaarskuwings en aanpasbare leiding hou jou op koers en ouers ingelig.", phase4_name: "Loopbaankartering", phase4_head: "Jou plan ontwikkel soos j\u00fd groei.", phase4_body: "Loopbaanaanbevelings word opgedateer soos jou punte verbeter, belange verskuif en die arbeidsmark verander.", phase5_name: "Aansoekbestuursstelsel", phase5_head: "Een portaal. Elke instelling.", phase5_body: "Doen aansoek by universiteite, TVET-kolleges en vaardigheidsprogramme — met passings-intelligensie wat elke stap lei.", phase6_name: "Instellingpassing", phase6_head: "Die regte instelling vind jou.", phase6_body: "Instellings kry toegang tot jou profiel en neem kontak op op grond van werklike passing, nie blinde massa-werwing nie.",
    eco_label: "Wie Dit Dien", eco_h2_1: "Gebou vir elke student.", eco_h2_2: "Ondersteun deur", eco_h2_3: "almal rondom hulle.", eco_sub: "Een platform rondom die student gebou, ondersteun deur skole, ouers en universiteite. Studente kry altyd gratis toegang.", eco_s1_title: "Vir Studente", eco_s1_sub: "Elke kenmerk, altyd gratis.", eco_s1_cta: "Gratis vir elke leerder, altyd", eco_s1_f1: "KI-aangedrewe loopbaanprofiel", eco_s1_f2: "Persoonlike vakkeusaanbevelings", eco_s1_f3: "APS-teiken-opvolging en -voorspelling", eco_s1_f4: "Universiteits- en TVET-aansoekknoop", eco_s1_f5: "Gamifiseerde loopbaanverkeningsmissies", eco_s1_f6: "Persoonlike ontwikkelingsportfolio", eco_s2_title: "Vir Skole", eco_s2_sub: "Skoolgeleide leiding, vereenvoudig.", eco_s2_cta: "Bemagtig skoolberaders", eco_s2_f1: "Leerder-dashboards vir elke klas", eco_s2_f2: "Graad 9-beradingsinfrastruktuur", eco_s2_f3: "Outomatiese leidingswerkvloeie", eco_s2_f4: "Vroe\u00eb waarskuwings vir risiko-leerders", eco_s2_f5: "Prestasie-normvergelyking per skool", eco_s2_f6: "Skoolwye verslagdoeningsinstrumente", eco_s3_title: "Vir Ouers", eco_s3_sub: "Bly naby jou kind se toekoms.", eco_s3_cta: "Sigbaarheid wanneer dit saak maak", eco_s3_f1: "Intydse akademiese vorderingsaansig", eco_s3_f2: "Vroe\u00eb agterstands-waarskuwings", eco_s3_f3: "Loopbaanpad-opdaterings", eco_s3_f4: "APS-teiken-monitering", eco_s3_f5: "Aansoekstatusopvolging", eco_s3_f6: "Loopbaangereedheidsverslae", eco_s4_title: "Vir Universiteite & TVETs", eco_s4_sub: "Vind die regte studente, vinniger.", eco_s4_cta: "Slimmer studentwerwing", eco_s4_f1: "Voorafgekwalifiseerde studentepyplyne", eco_s4_f2: "Studentesukses-waarskynlikheidstellings", eco_s4_f3: "Passende werwingsinstrumente", eco_s4_f4: "Gereedheidsanalitika per program", eco_s4_f5: "Slimmer toelatingsintelligensie", eco_s4_f6: "Programaanvraag-neiningsdata",
    who_label: "Vir Wie Dit Is", who_h2: "Gebou vir elke stadium van jou reis.", who_sub: "Of jy nou matriek skryf, eerstejaars navigeer of jou honneurs voltooi \u2014 YourUniverse pas aan by jou vlak en jou doelwitte.", who_p1_title: "Die Matriekstudent", who_p1_quote: "Ek het \u2019n universiteit in gedagte en ek moet werklik inkom.", who_p1_body: "YourUniverse karteer jou studieplan direk na jou teikeninstelling se toelatingsvereistes. Jy studeer wat tel, op die manier wat tel.", who_p2_title: "Die Eerstejaarstudent", who_p2_quote: "Universiteit is \u2019n heeltemal ander w\u00ebreld en ek was nie gereed nie.", who_p2_body: "Die sprong van matriek na universiteit is sonder ondersteuning brutaal moeilik. YourUniverse bou die akademiese gewoontes en struktuur wat eerstejaarstudente nodig het om te oorleef en te floreer.", who_p3_title: "Die Nagraadse Leerder", who_p3_quote: "Ek het fokus, struktuur en \u2019n manier nodig om langtermynvordering op te volg.", who_p3_body: "Diep werk vereis \u2019n ander soort ondersteuning. YourUniverse bied gefokusde sessies, navorsingskontrolelys en akademiese skryfgereedskap vir nagraadse leerders.",
    waitlist_label: "Vroe\u00eb Toegang", waitlist_h2_1: "Sluit aan by die", waitlist_h2_2: "eerste kohort.", waitlist_sub: "Beperkte vroe\u00eb toegang vir SA-skole en leerders. Wees eerste in die ry.", wait_type_label: "Ek is \u2019n", wait_type_heading: "As wie sluit jy aan?", wait_t_student: "Student", wait_t_student_sub: "Graad 9 \u2013 Nagraads", wait_t_parent: "Ouer", wait_t_parent_sub: "Ondersteun my kind", wait_t_school: "Opvoeder / Skool", wait_t_school_sub: "Laer- of ho\u00ebrskool", wait_t_inst: "Universiteit / TVET", wait_t_inst_sub: "Ho\u00ebr onderwys", wait_step: "Stap", wait_of: "van", wait_review_lbl: "Hersiening", wait_firstname_q: "Wat is jou voornaam?", wait_firstname_hint: "Ons sal jou ervaring op grond van jou naam personaliseer.", wait_firstname_ph: "bv. Amahle", wait_surname_q: "Wat is jou van?", wait_surname_ph: "bv. Dlamini", wait_email_q: "Wat is jou e-posadres?", wait_email_hint: "Ons stuur jou bevestiging en stel jou in kennis by bekendstelling.", wait_email_ph: "jy@voorbeeld.co.za", wait_email_nospam: "Geen gemorspos nie. Teken enige tyd uit.", wait_org_school_q: "Watter skool verteenwoordig jy?", wait_org_parent_q: "By watter skool is jou kind? (opsioneel)", wait_org_inst_q: "Van watter instelling kom jy?", wait_org_hint: "Dit help ons om jou by die regte groep te pas.", wait_org_school_ph: "bv. Parktown Seuns Hoerskool", wait_org_parent_ph: "bv. St Mary's DSG", wait_org_inst_ph: "bv. Universiteit van Pretoria", wait_back: "Terug", wait_continue: "Aanhou", wait_review_btn: "Hersien", wait_rev_heading: "Lyk goed", wait_rev_sub: "Gaan jou besonderhede deur voor jy by die waglys aansluit.", wait_rev_type: "Tipe", wait_rev_name: "Naam", wait_rev_email: "E-pos", wait_rev_org: "Organisasie", wait_submit: "Bevestig en sluit by waglys aan", wait_joining: "Besig om aan te sluit\u2026", wait_footer: "Gemaak in Suid-Afrika \u00b7 Gratis vir elke student, altyd.", wait_success_h: "Jy is op die lys.", wait_success_p: "\u2019n Bevestiging is onderweg na", wait_success_end: "Jy is deel van die infrastruktuur wat Afrika se opvoedkundige toekoms help vorm.", wait_press_enter: "Druk", wait_to_continue: "om voort te gaan",
    schools_badge: "Institusionele Vennote", schools_h1_1: "Gebou vir", schools_h1_2: "elke", schools_h1_3: "belanghebbende in onderwys", schools_sub: "Studente leer. Skole lei. Universiteite werf. Besighede ontdek talent. YourUniverse bedien die hele ekosisteem \u2014 een platform, een missie.",
    plat_page_badge: "Platformtegnologie", plat_page_h1_1: "Ses intelligensiesisteme.", plat_page_h1_2: "Een verenigde platform.", plat_page_sub: "Van grond af gebou vir Suid-Afrikaanse leerders, skole en instellings. Geen aangepaste buitelandse sagteware nie — doelgebou vir die NSS, die IEB en SA se unieke loopbaanlandskap.",
    foot_tagline: "Suid-Afrika se eerste opvoedkundige besluitintelligensie-platform — lei leerders van Graad 9 tot graduering en verder.", foot_product_of: "\u2019n Produk van", foot_col_platform: "Platform", foot_col_company: "Maatskappy", foot_col_legal: "Regsake", foot_how_it_works: "Hoe Dit Werk", foot_ai_features: "KI-Kenmerke", foot_for_schools: "Vir Skole", foot_for_inst: "Vir Instellings", foot_req_access: "Versoek Vroe\u00eb Toegang", foot_about: "Oor Ons", foot_lynxio: "Lynxio Tech", foot_careers: "Loopbane", foot_privacy: "Privaatheidsbeleid", foot_terms: "Diensbepalings", foot_data: "Databeskerming", foot_copyright: "Alle regte voorbehou. Gebou in Suid-Afrika.",
    loading_label: "Initialiseer", footer_rights: "Alle regte voorbehou.",
    waitlist_name: "Volle naam", waitlist_email: "E-posadres", waitlist_role: "Ek is \u2019n...", waitlist_cta: "Versoek Vroe\u00eb Toegang",
  },
};

type TranslationKey = keyof typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => translations.en[k],
});

const STORAGE_KEY = "yu_lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  /* Restore persisted preference on mount */
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as Lang | null;
      if (saved === "en" || saved === "af") setLangState(saved);
    } catch {
      /* localStorage unavailable (SSR or private browsing) – silent */
    }
  }, []);

  /* Persist selection and sync <html lang> attribute */
  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem(STORAGE_KEY, l); } catch { /* silent */ }
    if (typeof document !== "undefined") document.documentElement.lang = l;
  };

  const t = (key: TranslationKey): string =>
    (translations[lang][key] ?? translations.en[key]) as string;

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
